using PasswordlessAuthentication.Samples;
using Xunit;

namespace PasswordlessAuthentication.EntityFrameworkCore.Applications;

[Collection(PasswordlessAuthenticationTestConsts.CollectionDefinitionName)]
public class EfCoreSampleAppServiceTests : SampleAppServiceTests<PasswordlessAuthenticationEntityFrameworkCoreTestModule>
{

}
