using Xunit;

namespace PasswordlessAuthentication.EntityFrameworkCore;

[CollectionDefinition(PasswordlessAuthenticationTestConsts.CollectionDefinitionName)]
public class PasswordlessAuthenticationEntityFrameworkCoreCollection : ICollectionFixture<PasswordlessAuthenticationEntityFrameworkCoreFixture>
{

}
