using PasswordlessAuthentication.EntityFrameworkCore;
using Xunit;

namespace PasswordlessAuthentication.EntityFrameworkCore;

public class PasswordlessAuthenticationEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<PasswordlessAuthenticationEntityFrameworkCoreFixture>
{

}
